### ISSUE TITLE
Keyboard Configuration on hpsx264? 

### ISSUE THREAD

**Issue by HalogenGam3r** [Zero3K/hpsx64#1]
I tried to change the keys for the games, but it crashed.
Any fixes?

**Comment by Zero3K** [comment]
It doesn't support using the keyboard. How did you get it to crash?

**Comment by HalogenGam3r** [comment]
I clicked the button X, and it just crashed after that. (I am using Windows 10.)

**Comment by Zero3K** [comment]
Do you have a gamepad connected? 

EDIT: I was able to replicate your crash by "disconnecting" my gamepad. I will let whoever happens to fix the crash and improve it know about this crash.

**Comment by HalogenGam3r** [comment]
No, I just want to test a game with the keyboard. Sad that it doesn't support it.
