### ISSUE TITLE
What's happening with these projects?

### ISSUE THREAD

**Issue by jarrodnorwell** [Zero3K/hpsx64#3]
Recently noticed a comment from you on another repository regarding the PS1 and PS2 emulators here and was wondering what is happening with them?

**Comment by Zero3K** [comment]
They are still being worked on by the developer. I was just seeing if other developers could fix some issues before he gets around to fixing them.

**Comment by jarrodnorwell** [comment]
I'm currently looking at the project and notice a few issues, likely due to the latest MSVC though. What have you found so far?

**Comment by Zero3K** [comment]
https://sourceforge.net/p/hpsx64/discussion/general/thread/ecdf4fe105/
https://sourceforge.net/p/hpsx64/discussion/general/thread/b1adc94366/
https://sourceforge.net/p/hpsx64/discussion/general/thread/b82837be28/

PS2 emulation is still slow.
